# -*- coding: utf-8 -*-
"""exercicios-entendendo-algoritmos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDtNFqqbmmR4m4nNI1vl67JHg00f6WII

# Ordenação por seleção
"""

def buscaMenor(arr):
    menor = arr[0] #armazena o menor valor
    menor_indice = 0 #armazena o índice do menor valor
    for i in range(1, len(arr)):
        if arr[i] < menor:
            menor = arr[i]
            menor_indice = i
    return menor_indice

def ordenacaoporSelecao(arr): #ordenacao em um array
    novoArr = []
    for i in range(len(arr)):
        menor_indice = buscaMenor(arr)  # Encontra o índice do menor elemento no array
        novoArr.append(arr.pop(menor_indice))
    return novoArr

print(ordenacaoporSelecao([5, 3, 6, 2, 10]))

print(ordenacaoporSelecao([11, 22, 6, 2, 10]))

"""# Recursividade"""

def fat(x):
  if x == 1:
    return 1
  else:
    return x*fat(x-1)

fat(3)

fat(11)

